name: BLADE AND SOUL
display-name: "§6剑灵"
camp: 好人阵营
description: "以剑为引"
skill1-name: "§6【直线刺击】§f对周围(r=6)玩家0.5心真伤+速度3 击中缓慢 7s 可叠加4次"
skill2-name: "§6【横向扫荡】§f对周围(r=6)玩家1心真伤 7s 可叠加4次"
skill3-name: "§6【瞬时防御】§f缓慢3+抗性4+回3心 20s CD"
skill4-name: "§6【剑灵】§f一次性技能 消耗技能1/2各4层 对周围(r=8)每0.1s造成0.5心真伤+击退 持续1.4s"
passive-name: "无"
