name: COUNT
display-name: "§5伯爵"
camp: 狼人阵营
description: "鲜血王庭"
skill1-name: "§5【撕咬】§f对周围(r=5)玩家造成3次真伤(每次2心)+中毒 自己回血4心 狂热时每次3心+凋零 自己回6心 CD10s"
skill2-name: "§5【狂热之血】§f切换形态 进入/退出狂热(攻速1 速度2 跳跃1+红色特效) 每3s损失3.5心 CD3s"
skill3-name: "§5【蝙蝠唤取】§f需处于狂热形态 隐身3s并召唤20只蝙蝠 CD20s"
passive-name: "§5【吸血】§f对周围(r=5)玩家造成1心真伤+自己回2心 CD10s 狂热时1.5心 CD6s"
