name: HACKER
display-name: "§8黑客"
camp: 好人阵营
description: "数字世界的掌控者"
skill1-name: "§8【杀戮光环】§f需手持铁剑 自动开启 每0.2s对周围(r=10)玩家造成0.5心伤害(走原版普攻结算) 持续4s(自己同时凋零1 4s) 无技能钻石"
skill2-name: "§8【位置标记】§f标记当前位置 再次使用传送回"
passive-name: "§8【自动接入】§f手持铁剑时自动开启杀戮光环 放下铁剑自动关闭 无需技能钻石"
