name: SLIME
display-name: "§a史莱姆"
camp: 好人阵营
description: "分裂国度"
skill1-name: "无"
skill2-name: "无"
passive-name: "§a【三命】§f三次复活 初始:正常物资 跳跃5 / 第一条:仅有武器 跳跃3 血量上限7心 / 第二条:仅有小刀 跳跃1 血量上限5心 / 第三条:无物资 血量上限3心 不可拾取物资"
